version: "3.9"

services:
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    ports:
      - "80:80" # http traffic
      - "443:443" # https traffic
      - "443:443/udp" #http3 traffic
      - "2019:2019" # caddy uses for admin purposes
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
