version: "3.9"

services:
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    ports:
      - "80:80" # http traffic
      - "88:88" # http traffic
      - "443:443" # https traffic
      - "3000:3000" # testing
      - "443:443/udp" #http3 traffic
      - "2019:2019" # caddy uses for admin purposes
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:
networks:
  caddy:
    name: caddy
    driver: bridge
